language: node_js
node_js:
  - 0.10
install:
  - npm install -g bower
  - bower install
after_success:
  - npm install -g firebase-tools
  - echo "${FIREBASE_EMAIL}\n${FIREBASE_PASSWORD}" | firebase deploy